name: Dependency Security Gate

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'server/package.json'
      - 'server/package-lock.json'

  push:
    branches:
      - '**'
    paths:
      - 'server/package.json'
      - 'server/package-lock.json'

jobs:
  security-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install
        working-directory: ./server

      - name: Run Snyk Security Scan
        uses: snyk/actions/node@master
        with:
          args: test --severity-threshold=high --file=server/package.json
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}